[package]
name = "goldfish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5.8"
thrussh = "0.33.5"
regex = "1"
sha2 = "0.9.8"
pathdiff = "0.1.0"
